### ISSUE TITLE
open as page

### ISSUE THREAD

**Issue by AlishahMughal123** [Ademrobert/Wikipedia-Search-Engine#1]
Hello
Suggestion: change the name to wikipedia.github.io so easily to commit new changes & check for changes, directly to the web.

Thanks

**Comment by Ademrobert** [comment]
@AlishahMughal123 So you mean create Github pages?

**Comment by Ademrobert** [comment]
@AlishahMughal123 Oh okay now I understood 
Thanks for the suggestion
